---
title: "Lab 02 - Data Wrangling with `dplyr` - INSTRUCTIONS"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = TRUE )
```

# Overview

In this lab, you will practice using the `dplyr` package to manipulate and summarize data in R. 
The purpose of this lab is to develop familiarity with the **grammar of data manipulation** and build confidence using reproducible workflows to prepare data for analysis. 
Rather than making changes manually in a spreadsheet, you will use a sequence of `dplyr` commands to create a documented "recipe" for transforming raw data into useful information.

The lab has two parts. 
First, you will complete a series of data-wrangling tasks using data from a study by Claire Adida and colleagues entitled ["Diversity and violence during conflict migration: The Troubles in Northern Ireland"](https://doi.org/10.1017/psrm.2022.36 ).
The data are information about individuals murdered during a period of history in Nothern Ireland referred to as the "Troubles". 
The data are available in the `DWVpack` package and are called `troubles_fatalities`. 
For information, use the `?troubles_fatalities` command.
Second, you will repeat the process using the data you used for [Lab 1]().

By the end of the lab, you should be comfortable combining multiple `dplyr` verbs using the pipe (`|>`) to answer questions about a dataset.

# Tasks

## Part 1: Victims of Murder

For the `troubles_fatalities` data, answer the following prompts:  

  1. Identify the number of observations, number of variables, and what a single row represents.
  2. Use `select()` to create a smaller version of the dataset containing only the `age` and `sex` variables.
  3. Use `distinct()` to investigate the values of `sex` and `affiliation`.
  4. Use `filter()` to a subset of the data that is just **Catholic** victims, then a subset of victims that are **male** *and* **Protestant**, and finally a subset of victims that are **male** *or* **Younger than 18**.
  5. Use `arrange()` to sort the dataset by `age`.
  6. Use `mutate()` to create a new variable that captures whether a victim is a minor (i.e. younger than 18) or an adult (i.e. 18 years or older). If you get stuck here, take a look back at the use of the `ifelse()` function.
  7. Use `summarize()` to calculate the number of observations (`n()`) in the data and the **mean** for `age`.
  8. Use `group_by()` with `summarize()` to find the **mean** age for victims for each religious affiliation (i.e. use the `affiliation` variable).

## Part 2: Your Dataset

Now repeat the processes from Part 1 using the data you found in [Lab 1](), substituting the variables in your data. 
The goal is **not** to reproduce the exact commands from Part 1.
Rather, determine how the same data-wrangling tools can help you understand and prepare your own data.

## Analytical Briefing

In your briefing (approximately 3–5 minutes), focus on the data you used in **Part 2** and discuss what you learned through your data-wrangling process.
Here are some things you might discuss:  

  - Describe the variables you selected for your analysis and explain why they are useful for understanding the data.
  - Discuss any important patterns, categories, or potential data-quality issues you identified while examining and manipulating the data.
  - Interpret the results of your summary statistics and grouped summaries. Focus on what the results tell you about the data rather than simply reporting numerical values.
  - Discuss at least one finding that you think would be useful or interesting to an analyst working with these data.
  - Identify one additional question that you could investigate with this dataset in a future analysis.

### Expectations

Your briefing should demonstrate your understanding of how data manipulation can be used to explore and understand a dataset.
Focus on **what you learned from the data**, rather than simply describing the `dplyr` commands you used. 
For example, instead of stating that you "used `group_by()` and `summarize()` to calculate a mean," explain what differences you found between the groups and why those differences might be meaningful.
Your briefing should also demonstrate that you understand the structure and limitations of your dataset and can communicate your findings in a way that would be useful to an analyst.

____

<br>

# How to Submit

Download the [template for this lab](../labs/templates/lab-02-LastName.zip?raw=true) prior to beginning the lab. 

<br>

### Knitting to HTML

When you have completed your assignment using the template, click the "Knit" button to render your `.RMD` file into a `.HTML` report.

<br>

### Special Instructions

Upload your `.RMD`, `.HTML`, and `.MP4` files to the appropriate link for this assignment on the Canvas page for this course.

<br>

### Before You Submit

Remember to ensure the following before submitting your assignment.

  * Name your files using this format: **Lab-##-LastName.rmd**, **Lab-##-LastName.html**, **Lab-##-LastName.mp4**
  * Show both the solution for your code and write out your answers in the body text 
  * Verify that both files open correctly and that your video includes clear audio narration

See [Google's R Style Guide](https://google.github.io/styleguide/Rguide.xml) for examples of common conventions.

<br>
<br>

### Common Knitting Issues

`.RMD` files are knit into `.HTML` and other formats procedural, or line-by-line.

* An error in code when knitting will halt the process; error messages will tell you the specific line with the error
* Certain functions, like `install.packages()` or `setwd()`, are bound to cause errors in knitting 
* Altering a dataset or variable in one chunk will affect its use in all later chunks
* If an object is "not found", make sure it was created or loaded with `library()` in a previous chunk

**If All Else Fails:** If you cannot determine and fix the errors in a code chunk that's preventing you from knitting your document, add `eval = FALSE` inside the brackets of `{r}` at the beginning of a chunk to ensure that R does not attempt to evaluate it, that is: `{r eval = FALSE}`. This will prevent an erroneous chunk of code from halting the knitting process.  